[tool.black]
line-length=79
[tool.poetry]
name = "fuzz-lightyear"
version = "0.1.0"
description = "Blazing fast fuzzy text search for Python."
authors = ["Márton Kardos <power.up1163@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "fuzz_lightyear"}]

[tool.poetry.dependencies]
python = ">=3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
